[package]
name = "jorde/tgc2-rewrite"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[server-dependencies]
ProfileService = "brittonfischer/profileservice@2.1.5"
cmdr = "evaera/cmdr@1.11.0"

[dependencies]
debugLoggerUtil = "bubshayz/debugloggerutil@1.1.2"
Component = "bubshayz/component@1.6.0"
contextActionServiceUtil = "bubshurb/contextactionserviceutil@1.0.0"
Signal = "stravant/goodsignal@0.2.1"
loader = "sleitnick/loader@2.0.0"
Promise = "evaera/promise@4.0.0"
Trove = "sleitnick/trove@1.0.1"
Sift = "csqrl/sift@0.0.8"
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
Input = "sleitnick/input@2.3.0"