export type ShopConfig = {
	name: string,
	price: number,
	levelReq: number,
	description: string,
}

return {
	{
		name = "Sawed-Off Shotgun",
		price = 1000,
		levelReq = 5,
		description = "The Swiss Army knife of the underworld",
	},
	{
		name = "Katana",
		price = 1000,
		levelReq = 5,
		description = "Perfect for those who appreciate the art of subtlety in their mayhem.",
	},
	{
		name = "Double Barrel Shotgun",
		price = 2000,
		levelReq = 10,
		description = "Perfect for those indecisive moments when you can't choose between overkill and extreme overkill.",
	},
}
